Add output files and change tabs to spaces
Signed-off-by: Aviv Maayan <aviv.m@campus.technion.ac.il>

diff --git a/selfcheck-hw5 b/selfcheck-hw5
--- a/selfcheck-hw5
+++ b/selfcheck-hw5
@@ -10,108 +10,108 @@ command="./hw3 < t\$i.in >& t\$i.res"
 hostname="cscomp"
 tmpdir="selfcheck_tmp"
 if [ $( hostname ) != "$hostname" ]
-	then 
-	echo "This script is only intended to run on "$hostname" or "$hostname2"!" 
-	exit 
+    then 
+    echo "This script is only intended to run on "$hostname" or "$hostname2"!" 
+    exit 
 fi 
 
 if [ -z "$1" ]
-	then 
-	echo "Usage: $0 submission_file"
-	exit 
+    then 
+    echo "Usage: $0 submission_file"
+    exit 
 fi
 
 if [ ! -f "$1" ] 
-	then
-	echo "Submission zip file not found!" 
-	exit 
+    then
+    echo "Submission zip file not found!" 
+    exit 
 fi 
 
 rm -rf "$tmpdir" &> /dev/null 
 
 if [ -d "$tmpdir" ] 
-	then 
-	echo "Cannot clear tmp directory. Please delete '"$tmpdir"' manually and try again" 
-	exit 
+    then 
+    echo "Cannot clear tmp directory. Please delete '"$tmpdir"' manually and try again" 
+    exit 
 fi 
 
 mkdir "$tmpdir" &> /dev/null 
 unzip "$1" -d "$tmpdir" &> /dev/null 
 
 if [[ $? != 0 ]] 
-	then 
-	echo "Unable to unzip submission file!" 
-	exit
+    then 
+    echo "Unable to unzip submission file!" 
+    exit
 fi
 
 cd "$tmpdir"
 
 if [ ! -f scanner.lex ] 
-	then
-	echo "File scanner.lex not found!"
-	exit
+    then
+    echo "File scanner.lex not found!"
+    exit
 fi
 
 if [ ! -f parser.ypp ] 
-	then
-	echo "File parser.ypp not found!"
-	exit
+    then
+    echo "File parser.ypp not found!"
+    exit
 fi
 
 if [ ! -f hw3_output.cpp ] 
-	then
-	echo "File output.cpp not found!"
-	exit
+    then
+    echo "File output.cpp not found!"
+    exit
 fi
 
 if [ ! -f hw3_output.hpp ] 
-	then
-	echo "File output.hpp not found!"
-	exit
+    then
+    echo "File output.hpp not found!"
+    exit
 fi
 
 wget --no-check-certificate "$makefileurl" &> /dev/null
 if [ ! -f makefile ]
-	then
-		echo "Unable to download makefile!"
-		exit
+    then
+        echo "Unable to download makefile!"
+        exit
 fi
 
 make
 
 if [ ! -f hw5 ] 
-	then 
-	echo "Cannot build submission!" 
-	exit 
+    then 
+    echo "Cannot build submission!" 
+    exit 
 fi 
 
 wget --no-check-certificate "$testsurl" &> /dev/null 
 if [ ! -f $( basename "$testsurl" ) ] 
-	then 
-	echo "Unable to download tests!" 
-	exit 
+    then 
+    echo "Unable to download tests!" 
+    exit 
 fi
 
 unzip $( basename "$testsurl" ) &> /dev/null
 
 if [[ $? != 0 ]]
-	then 
-	echo "Unable to unzip tests!" 
-	exit 
+    then 
+    echo "Unable to unzip tests!" 
+    exit 
 fi 
 
 i="1"
 while [ $i -le $numtests ]
-	do
-		./hw5 < t$i.in 2>&1 > t$i.ll
-		lli t$i.ll > t$i.res
-		diff t$i.res t$i.out &> /dev/null
-		if [[ $? != 0 ]] 
-			then
-				echo "Failed test #"$i"!"
-				exit
-		fi
-		i=$[$i+1]
+    do
+        ./hw5 < t$i.in 2>&1 > t$i.ll
+        lli t$i.ll > t$i.res
+        diff t$i.res t$i.out &> /dev/null
+        if [[ $? != 0 ]] 
+            then
+                echo "Failed test #"$i"!"
+                exit
+        fi
+        i=$[$i+1]
 done
 
 cd - &> /dev/null
